### ISSUE TITLE
Not working on Next.js

### ISSUE THREAD

**Issue by rizshivalli** [chatscope/chat-ui-kit-react#146]
Getting this error on the fresh install of next.js and chat-ui-kit-react

installed dependencies

```` 
"dependencies": {
    "@chatscope/chat-ui-kit-react": "^2.0.0",
    "@chatscope/chat-ui-kit-styles": "^1.4.0",
    "next": "14.1.1",
    "react": "^18",
    "react-dom": "^18"
  }
````

````
 ⨯ node_modules/@chatscope/chat-ui-kit-react/dist/es/Scroll/ReactPerfectScrollbar.js (16:112) @ _inherits
 ⨯ TypeError: Super expression must either be null or a function
null
 at __webpack_require__ (/Users/rizwanshivalli/Desktop/Projects/chat/.next/server/webpack-runtime.js:33:42)
    at __webpack_require__ (/Users/rizwanshivalli/Desktop/Projects/chat/.next/server/webpack-runtime.js:33:42)
    at __webpack_require__ (/Users/rizwanshivalli/Desktop/Projects/chat/.next/server/webpack-runtime.js:33:42)
    at __webpack_require__ (/Users/rizwanshivalli/Desktop/Projects/chat/.next/server/webpack-runtime.js:33:42)
    at __webpack_require__ (/Users/rizwanshivalli/Desktop/Projects/chat/.next/server/webpack-runtime.js:33:42)
    at __webpack_require__ (/Users/rizwanshivalli/Desktop/Projects/chat/.next/server/webpack-runtime.js:33:42)
    at __webpack_require__ (/Users/rizwanshivalli/Desktop/Projects/chat/.next/server/webpack-runtime.js:33:42)
    at eval (./src/app/page.tsx:7:86)
    at (rsc)/./src/app/page.tsx (/Users/rizwanshivalli/Desktop/Projects/chat/.next/server/app/page.js:184:1)
    at Function.__webpack_require__ (/Users/rizwanshivalli/Desktop/Projects/chat/.next/server/webpack-runtime.js:33:42)
    at async Promise.all (index 0)
digest: "4058398674"
TypeError: Super expression must either be null or a function
    at _inherits (webpack-internal:///(rsc)/./node_modules/@chatscope/chat-ui-kit-react/dist/es/Scroll/ReactPerfectScrollbar.js:148:15)
    at eval (webpack-internal:///(rsc)/./node_modules/@chatscope/chat-ui-kit-react/dist/es/Scroll/ReactPerfectScrollbar.js:187:5)
    at eval (webpack-internal:///(rsc)/./node_modules/@chatscope/chat-ui-kit-react/dist/es/Scroll/ReactPerfectScrollbar.js:307:2)
    at (rsc)/./node_modules/@chatscope/chat-ui-kit-react/dist/es/Scroll/ReactPerfectScrollbar.js
````

**Comment by supersnager** [comment]
@rizshivalli How did you installed v2.0.0 if there is no package with that version?
Please upgrade to v2.0.3, and let me know if that helps.

You can also try to add ```'use client'``` to the file where components are used.

**Comment by rizshivalli** [comment]
Its working with ` 'use-client' ` but the styles are not getting applied.

````

"use client";
import styles from "@chatscope/chat-ui-kit-styles/dist/default/styles.min.css";
import {
  ChatContainer,
  MainContainer,
  Message,
  MessageInput,
  MessageList,
} from "@chatscope/chat-ui-kit-react";

export default function Home() {
  return (
    <div style={{ position: "relative", height: "500px" }}>
      <MainContainer>
        <ChatContainer>
          <MessageList>
            <Message
              model={{
                message: "Hello my friend",
                sentTime: "just now",
                sender: "Joe",
              }}
            />
          </MessageList>
          <MessageInput placeholder="Type message here" />
        </ChatContainer>
      </MainContainer>
    </div>
  );
}

````

<img width="1438" alt="Screenshot 2024-03-04 at 9 20 16 PM" src="https://github.com/chatscope/chat-ui-kit-react/assets/35989813/14545cd2-b9fb-4e33-b10e-d09aa47df276">

**Comment by Zakariaels** [comment]
Can you try the following ?
`import '@chatscope/chat-ui-kit-styles/dist/default/styles.min.css';
`

**Comment by rizshivalli** [comment]
Now working, Thank you
